
// try.pwc

fn Result<Int, String> doSomethingWrong() {
  return new Result<>("Something went wrong");
}

fn Result<Int, String> doSomethingRight() {
  return new Result<>(10);
}

fn Result<Int, String> callDoSomethingWrong() {
  const result = doSomethingWrong();
  const value = try result;
  println(value); // Unreachable code
}

fn Result<Int, String> callDoSomethingRight() {
  const result = doSomethingRight();
  const value = try result;
  println(value); // 10
}

fn Void main() {
  callDoSomethingWrong();
  callDoSomethingRight();
}
